import { Database } from "bun:sqlite";
import { Hono } from "hono";
import { EventEmitter } from "node:events";
import { existsSync, mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { resolve, extname, normalize, relative } from "node:path";
import { readFile, stat, readdir } from "node:fs/promises";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface KitManifest {
  id: string;
  name: string;
  version: string;
  description: string;
  icon: string;
  enabled: boolean;
}

export interface KitInfoDTO {
  id: string;
  name: string;
  description: string;
  icon: string;
  version: string;
  enabled: boolean;
}

export interface KitContext {
  kitId: string;
  db: Database;
  config: KitManifest;
  kitsDir: string;
}

export interface KitsServerConfig {
  dir: string;
}

// ---------------------------------------------------------------------------
// MIME types for serving kit frontend files
// ---------------------------------------------------------------------------

const MIME_TYPES: Record<string, string> = {
  ".html": "text/html; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".js": "text/javascript; charset=utf-8",
  ".mjs": "text/javascript; charset=utf-8",
  ".json": "application/json; charset=utf-8",
  ".png": "image/png",
  ".jpg": "image/jpeg",
  ".jpeg": "image/jpeg",
  ".gif": "image/gif",
  ".svg": "image/svg+xml",
  ".webp": "image/webp",
  ".ico": "image/x-icon",
  ".woff": "font/woff",
  ".woff2": "font/woff2",
  ".ttf": "font/ttf",
  ".wasm": "application/wasm",
};

// ---------------------------------------------------------------------------
// AGENTS.md content — auto-discovered by pi when cwd is under ~/.sam/kits/
// ---------------------------------------------------------------------------

const AGENTS_MD = `# Kit Development Guidelines

You are working on a **kit** — a self-contained mini-app with a React frontend and Hono backend.

## Project Structure

\`\`\`
<kitId>/
├── kit.json              # Manifest (id, name, description, icon, version, enabled)
├── client/               # React + Vite + Tailwind v4 frontend
│   ├── src/
│   │   ├── App.tsx       # Main component
│   │   ├── main.tsx      # Entry point
│   │   ├── index.css     # Tailwind + shadcn/ui theme variables
│   │   ├── lib/utils.ts  # cn() helper
│   │   └── components/ui/  # shadcn/ui components (added via CLI)
│   ├── components.json   # shadcn CLI config
│   └── vite.config.ts    # Vite config with @/ alias
├── server/
│   └── index.ts          # Hono backend (default export)
└── dist/                 # Built frontend (generated by vite build)
\`\`\`

## Frontend

### UI Components
Use **shadcn/ui** for all UI components. Add components via:
\`\`\`bash
bunx shadcn@latest add button card input select badge table tabs dialog sonner
\`\`\`

Import components from \`@/components/ui/\`:
\`\`\`tsx
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
\`\`\`

Use the \`cn()\` utility for conditional classes:
\`\`\`tsx
import { cn } from "@/lib/utils";
<div className={cn("p-4", isActive && "bg-accent")} />
\`\`\`

### Styling
- Tailwind CSS v4 is pre-configured with shadcn/ui CSS variables
- Use shadcn's semantic color tokens: \`bg-background\`, \`text-foreground\`, \`bg-primary\`, \`text-muted-foreground\`, etc.
- Do **not** install other UI libraries (Material UI, Chakra, Ant Design, etc.)

### Layout
Kits run in a desktop iframe AND an iOS WKWebView — always design mobile-first:
- Start with a single-column layout that works on small screens, then enhance for wider viewports with \`sm:\`, \`md:\`, \`lg:\`
- Use \`w-full max-w-lg mx-auto\` (or similar) to center content and prevent overly wide layouts on desktop
- Tap targets must be at least 44×44px — use \`min-h-11 min-w-11\` on interactive elements
- Avoid hover-only interactions — anything revealed on hover must also be accessible via tap
- Use \`gap-*\` and \`p-4\` (not \`p-1\` or \`p-2\`) for comfortable touch spacing
- Prefer vertical scrolling over horizontal scrolling
- Test that text is readable without zooming (minimum \`text-sm\` / 14px)

### API Calls
Use \`kit.fetch()\` from \`@/lib/kit\` for all backend calls. It handles routing automatically — **use the same paths as your Hono routes**:
\`\`\`tsx
import { kit } from "@/lib/kit";

const res = await kit.fetch("/items");
const data = await res.json();
\`\`\`

**IMPORTANT:** Never use \`fetch()\` directly for kit API calls. Always use \`kit.fetch()\` — it ensures the correct routing prefix is applied.

## Backend

The backend is a **Hono** router exported as the default function from \`server/index.ts\`:

\`\`\`ts
import { Hono } from "hono";
import type { KitContext } from "../../../agent/src/kits-server";

export default function(ctx: KitContext): Hono {
  const app = new Hono();

  app.get("/items", (c) => {
    const rows = ctx.db.prepare("SELECT * FROM my_items").all();
    return c.json(rows);
  });

  return app;
}
\`\`\`

- **Frontend and backend use the same paths.** If the backend defines \`app.get("/items")\`, the frontend calls \`kit.fetch("/items")\`.
- \`ctx\` provides: \`kitId\`, \`db\` (shared SQLite), \`config\` (manifest), \`kitsDir\`

## Database

All kits share a single **SQLite** database via \`ctx.db\` (using Bun's built-in SQLite driver).

- **Namespace tables** with a prefix to avoid collisions (e.g. \`mykit_items\`, \`mykit_settings\`)
- **WAL mode** and **foreign keys** are already enabled
- **Use prepared statements** — never interpolate user input into SQL:
  \`\`\`ts
  // Good
  ctx.db.prepare("SELECT * FROM items WHERE id = ?").get(id);
  // Bad — SQL injection risk
  ctx.db.prepare(\\\`SELECT * FROM items WHERE id = \\\${id}\\\`).get();
  \`\`\`
- Create tables with \`IF NOT EXISTS\` so the kit is idempotent on reload

## Build & Reload

After making changes:
1. **Build** the frontend: the \`build\` action runs \`vite build\` in \`client/\`
2. **Reload** the backend: the \`reload\` action hot-reloads the Hono router

Both are triggered via the \`manage_kit\` tool — you don't need to run them manually.
`;

// ---------------------------------------------------------------------------
// KitsServer
// ---------------------------------------------------------------------------

export class KitsServer extends EventEmitter {
  private db: Database;
  private routers = new Map<string, Hono>();
  private manifests = new Map<string, KitManifest>();
  private kitsDir: string;

  constructor(config: KitsServerConfig) {
    super();
    this.kitsDir = config.dir;
    mkdirSync(this.kitsDir, { recursive: true });

    // Open or create the shared SQLite database
    const dbPath = resolve(this.kitsDir, "kits.db");
    this.db = new Database(dbPath, { create: true });
    this.db.exec("PRAGMA journal_mode = WAL");
    this.db.exec("PRAGMA foreign_keys = ON");
  }

  /** Scan kits directory and load all enabled kits. */
  async init(): Promise<void> {
    if (!existsSync(this.kitsDir)) return;

    // Scaffold shared UI library if not present
    this.ensureSharedLibrary();

    const entries = readdirSync(this.kitsDir);
    for (const entry of entries) {
      const kitDir = resolve(this.kitsDir, entry);
      const manifestPath = resolve(kitDir, "kit.json");
      if (!existsSync(manifestPath)) continue;

      try {
        const manifest = JSON.parse(readFileSync(manifestPath, "utf-8")) as KitManifest;
        this.manifests.set(manifest.id, manifest);
        if (manifest.enabled !== false) {
          await this.loadKit(manifest.id);
        }
      } catch (err) {
        console.warn(`[kits] Failed to load kit from ${entry}:`, err);
      }
    }

    const loaded = [...this.routers.keys()];
    if (loaded.length > 0) {
      console.log(`[kits] Loaded ${loaded.length} kit(s): ${loaded.join(", ")}`);
    }
  }

  /** Load a kit's backend module and mount its router. */
  async loadKit(kitId: string): Promise<void> {
    const kitDir = resolve(this.kitsDir, kitId);
    const serverEntry = resolve(kitDir, "server", "index.ts");

    if (!existsSync(serverEntry)) {
      console.warn(`[kits] Kit "${kitId}" has no server/index.ts — skipping backend`);
      return;
    }

    // Read manifest if not cached
    if (!this.manifests.has(kitId)) {
      const manifestPath = resolve(kitDir, "kit.json");
      const manifest = JSON.parse(readFileSync(manifestPath, "utf-8")) as KitManifest;
      this.manifests.set(kitId, manifest);
    }

    const ctx: KitContext = {
      kitId,
      db: this.db,
      config: this.manifests.get(kitId)!,
      kitsDir: this.kitsDir,
    };

    try {
      const mod = await import(serverEntry);
      const createRouter = mod.default ?? mod;
      const router = createRouter(ctx);
      this.routers.set(kitId, router);
      this.emit("kitsChanged", "loaded", kitId);
    } catch (err) {
      console.error(`[kits] Failed to load backend for kit "${kitId}":`, err);
    }
  }

  /** Unload a kit's backend router. */
  async unloadKit(kitId: string): Promise<void> {
    this.routers.delete(kitId);
    this.emit("kitsChanged", "unloaded", kitId);
  }

  /** Reload a kit — unload then load again, busting the module cache. */
  async reloadKit(kitId: string): Promise<void> {
    await this.unloadKit(kitId);

    // Clear Bun's module cache for the kit's server files
    const kitDir = resolve(this.kitsDir, kitId, "server");
    const registry = require.cache ?? (Loader as any)?.registry;
    if (registry && typeof registry === "object") {
      for (const key of Object.keys(registry)) {
        if (key.includes(kitDir)) {
          delete registry[key];
        }
      }
    }

    // Re-read manifest in case it changed
    const manifestPath = resolve(this.kitsDir, kitId, "kit.json");
    if (existsSync(manifestPath)) {
      const manifest = JSON.parse(readFileSync(manifestPath, "utf-8")) as KitManifest;
      this.manifests.set(kitId, manifest);
    }

    await this.loadKit(kitId);
  }

  /** Build a kit's frontend using Vite. */
  async buildKit(kitId: string): Promise<void> {
    const clientDir = resolve(this.kitsDir, kitId, "client");
    if (!existsSync(clientDir)) return;

    const packageJsonPath = resolve(clientDir, "package.json");
    if (!existsSync(packageJsonPath)) return;

    // Install deps if node_modules doesn't exist
    const nodeModulesDir = resolve(clientDir, "node_modules");
    if (!existsSync(nodeModulesDir)) {
      console.log(`[kits] Installing dependencies for kit "${kitId}"...`);
      const installProc = Bun.spawnSync(["bun", "install"], { cwd: clientDir });
      if (installProc.exitCode !== 0) {
        console.error(`[kits] Failed to install deps for kit "${kitId}":`, installProc.stderr.toString());
        return;
      }
    }

    console.log(`[kits] Building frontend for kit "${kitId}"...`);
    const buildProc = Bun.spawnSync(["bunx", "vite", "build"], { cwd: clientDir });
    if (buildProc.exitCode !== 0) {
      console.error(`[kits] Failed to build kit "${kitId}":`, buildProc.stderr.toString());
      return;
    }
    console.log(`[kits] Built kit "${kitId}" successfully.`);
    this.emit("kitsChanged", "built", kitId);
  }

  /** Get all kit manifests. */
  getKits(): KitInfoDTO[] {
    const kits: KitInfoDTO[] = [];
    // Re-scan directory for fresh data
    if (!existsSync(this.kitsDir)) return kits;

    const entries = readdirSync(this.kitsDir);
    for (const entry of entries) {
      const manifestPath = resolve(this.kitsDir, entry, "kit.json");
      if (!existsSync(manifestPath)) continue;
      try {
        const manifest = JSON.parse(readFileSync(manifestPath, "utf-8")) as KitManifest;
        kits.push({
          id: manifest.id,
          name: manifest.name,
          description: manifest.description,
          icon: manifest.icon,
          version: manifest.version,
          enabled: manifest.enabled !== false,
        });
      } catch {
        // skip malformed manifests
      }
    }
    return kits;
  }

  // ---------------------------------------------------------------------------
  // HTTP request handler
  // ---------------------------------------------------------------------------

  async handleRequest(req: Request): Promise<Response> {
    const url = new URL(req.url);
    const pathname = url.pathname;

    // CORS headers for cross-origin requests (Tauri dev mode)
    const corsHeaders = {
      "Access-Control-Allow-Origin": "*",
      "Access-Control-Allow-Methods": "GET, POST, PUT, DELETE, OPTIONS",
      "Access-Control-Allow-Headers": "Content-Type",
    };

    // Handle CORS preflight
    if (req.method === "OPTIONS") {
      return new Response(null, { status: 204, headers: corsHeaders });
    }

    // GET /kits — list all kits
    if (pathname === "/kits" || pathname === "/kits/") {
      return Response.json(this.getKits(), { headers: corsHeaders });
    }

    // Extract kit ID from path: /kits/<kitId>/...
    const match = pathname.match(/^\/kits\/([a-zA-Z0-9_-]+)(\/.*)?$/);
    if (!match) {
      return new Response("Not Found", { status: 404, headers: corsHeaders });
    }

    const kitId = match[1];
    const subPath = match[2] ?? "/";

    // API routes: /kits/<kitId>/api/...
    if (subPath.startsWith("/api")) {
      const router = this.routers.get(kitId);
      if (!router) {
        return Response.json({ error: `Kit "${kitId}" not loaded or has no backend` }, { status: 404, headers: corsHeaders });
      }

      // Rewrite the request URL to strip the /kits/<kitId>/api prefix
      // so the kit's Hono router sees clean paths like /quote, /todos
      const routePath = subPath.replace(/^\/api/, "") || "/";
      const rewrittenUrl = new URL(routePath, url.origin);
      rewrittenUrl.search = url.search;
      const rewrittenReq = new Request(rewrittenUrl.toString(), {
        method: req.method,
        headers: req.headers,
        body: req.body,
      });

      return router.fetch(rewrittenReq);
    }

    // Static files: /kits/<kitId>/... — serve from dist/ directory
    return this.serveKitStatic(kitId, subPath);
  }

  // ---------------------------------------------------------------------------
  // Shared UI library scaffolding
  // ---------------------------------------------------------------------------

  private ensureSharedLibrary(): void {
    // Scaffold AGENTS.md for pi auto-discovery
    const agentsMdPath = resolve(this.kitsDir, "AGENTS.md");
    if (!existsSync(agentsMdPath)) {
      writeFileSync(agentsMdPath, AGENTS_MD);
      console.log("[kits] Scaffolded AGENTS.md");
    }
  }

  // ---------------------------------------------------------------------------
  // Static file serving for kit frontends
  // ---------------------------------------------------------------------------

  private async serveKitStatic(kitId: string, subPath: string): Promise<Response> {
    const distDir = resolve(this.kitsDir, kitId, "dist");
    if (!existsSync(distDir)) {
      return new Response("Kit frontend not built", { status: 404 });
    }

    // Resolve path and guard against traversal
    let filePath = resolve(distDir, "." + normalize("/" + decodeURIComponent(subPath)));
    if (!filePath.startsWith(distDir)) {
      return new Response("Forbidden", { status: 403 });
    }

    try {
      let st = await stat(filePath);

      // Serve index.html for directories
      if (st.isDirectory()) {
        filePath = resolve(filePath, "index.html");
        st = await stat(filePath);
      }

      const ext = extname(filePath).toLowerCase();
      const contentType = MIME_TYPES[ext] ?? "application/octet-stream";

      return new Response(Bun.file(filePath), {
        headers: {
          "Content-Type": contentType,
          "Cache-Control": "no-store, no-cache",
        },
      });
    } catch {
      // SPA fallback — serve index.html for any unknown path
      const indexPath = resolve(distDir, "index.html");
      try {
        return new Response(Bun.file(indexPath), {
          headers: {
            "Content-Type": "text/html; charset=utf-8",
            "Cache-Control": "no-store, no-cache",
          },
        });
      } catch {
        return new Response("Not Found", { status: 404 });
      }
    }
  }
}
